- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClientConfig.java
- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClientFactory.java
- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClientImpl.java
Makes schema registry client auto closable.
Adds namespace as a factory method param rather than a config param so that users are explicitly aware of the namespace with which they are creating a client. 
Fixes #50 
Adds new factory method that takes the namespace rather than taking it from the ClientConfig. 
NA
> Issue 50: Make schema registry client autoclosable and add namespace to factory method

- build.gradle
- checkstyle/import-control.xml
- gradle.properties
- server/src/main/java/io/pravega/schemaregistry/service/SchemaRegistryService.java
Use everit.json.SchemaLoader to parse the json schema to verify that it is supported for schemas that follow draft specifications from 4 6 or 7.
Fixes #55 
Jackson's JsonSchema module supports Json schema draft 3. Draft 4 to 7 have some additional incompatible changes. JsonSchema is not able to parse a schema which conforms to versions 4 to 7 if they use any keywords that is not present in draft 3. 
So we first try to parse the schema using JsonSchema and if it fails, we attempt to parse it using SchemaLoader. 
If both fail, the schema is considered invalid. 
TBD
> Issue 55: Support for Json schema draft 4 to 7

- build.gradle
- contract/src/main/java/io/pravega/schemaregistry/contract/data/CodecType.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/Compatibility.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/EncodingInfo.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/GroupHistoryRecord.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/GroupProperties.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/SchemaInfo.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/SchemaWithVersion.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/SerializationFormat.java
- contract/src/main/java/io/pravega/schemaregistry/contract/data/VersionInfo.java
- contract/src/test/java/io/pravega/schemaregistry/contract/transform/ContractTest.java
Adds precondition checks to service model objects which includes checks for size limits on objects. 
Fixes #63 
Adds precondition checks on service model objects
Unit test added
> Issue 63: Add precondition checks to service model objects

- gradle/maven.gradle
Fix maven.gradle with schema registry info and remove pravega prefix from artifacts
Fixes #82 
1. removes "pravega" prefix before the artifactid. 
2. change the source control to give schema registry repo uri
(Optional: steps to verify that the changes are effective)
> Issue 82: Specify schema registry repo in maven.gradle and remove pravega prefix 

- server/src/main/java/io/pravega/schemaregistry/server/rest/RestServer.java
- server/src/main/java/io/pravega/schemaregistry/server/rest/ServiceConfig.java
- server/src/main/java/io/pravega/schemaregistry/service/Config.java
- server/src/test/java/io/pravega/schemaregistry/server/rest/ConfigTest.java
Fixes bug in ServiceConfig for configuring tls certificate and password file paths
Fixes #89 
Fixes bug in service config for configuring tls certificate and password file paths
Unit test for service config added.
> Issue 89: Fix bug in service config for configuring tls certificate and password file paths

- contract/src/main/java/io/pravega/schemaregistry/contract/transform/ModelHelper.java
- contract/src/test/java/io/pravega/schemaregistry/contract/transform/ModelHelperTest.java
- test/src/test/java/io/pravega/schemaregistry/integrationtest/TestEndToEnd.java
Fixes class cast exception in modelhelper for Compatibility.Backwardtill and Compatibility.forwardTill
Fixes #103 
When we use compatibility policy.backwardtill or forwardtill the modelhelper is using the incorrect object which causes class cast exception.
Unit test and integration test added
> Issue 103: Class cast Exception in ModelHelper for Compatibility.backwardTill

- .travis.yml
Publishes snapshot artifacts to jfrog as part of travis master builds. 
Fixes #92 
Adds the snapshot job to travis.yaml which calls gradle publish task on jcenterSnapshot repository. 
It also adds a javadoc stage in travis jobs. 
Artifacts should be published to travis.
> Issue 92: Publish SNAPSHOT artifacts to jfrog repository 

- contract/src/main/java/io/pravega/schemaregistry/contract/transform/ModelHelper.java
- contract/src/test/java/io/pravega/schemaregistry/contract/transform/ModelHelperTest.java
- test/src/test/java/io/pravega/schemaregistry/integrationtest/TestEndToEnd.java
Fixes class cast exception in modelhelper for Compatibility.Backwardtill and Compatibility.forwardTill
Fixes #103 
When we use compatibility policy.backwardtill or forwardtill the modelhelper is using the incorrect object which causes class cast exception.
Unit test and integration test added
> Issue 103: Class cast Exception in ModelHelper

- serializers/shared/src/main/java/io/pravega/schemaregistry/serializer/shared/impl/AbstractDeserializer.java
- serializers/src/test/java/io/pravega/schemaregistry/serializers/SerializerTest.java
- test/src/test/java/io/pravega/schemaregistry/integrationtest/TestPravegaClientEndToEnd.java
Fixes a bug in abstract deserializer where we progress the position by array offset. 
Fixes #114 
Fixes the bug in abstract deserializer to not use array offset. And also makes sure that the code correctly works when bytebuffer is not backed by array. 
Unit test and integration test added.
> Issue 114: AbstractDeserializer should not set positon to arrayOffset

- build.gradle
Removes relocation for avro protobuf and json (jackson and everit)
Fixes #122 
Updates build.gradle to not shade avro protobuf and json
These dependencies should not be shaded
> Issue 122: Do not relocate avro protobuf and json dependencies

- build.gradle
Removes relocation for Avro, Protobuf and JSON (Jackson and Everit).
Cherry pick 63c5eba5fb99b62e0e3e43dae9a9db652f0fd11a (#123 ) into r0.1
Fixes #124 
Cherry picks
> Issue 122: Do not relocate avro protobuf and json dependencies (#123)

- gradle.properties
Change master version to 0.2 snapshot in gradle.properties
Fixes #126 
Change master version to 0.2 snapshot in gradle.properties
> Issue 126: Change master version to 0.2 snapshot

- build.gradle
- gradle/maven.gradle
Change groupId from io.pravega.schemaregistry to io.pravega so that it shows up in the same group in maven.
Fixes #130 
Changes groupId from io.pravega.schemaregistry to io.pravega in build.gradle
Also adds schemaregistry prefix on all artifacts produced by schema registry
Artifacts should be produced with group id io.pravega and artifacts should have schemaregistry prefix
> Issue 130: Change project's groupId

- gradle.properties
- gradle/java.gradle
Changes pravega version to 0.8.0 in gradle.properties.
Fixes #134 
Changes pravega version to 0.8.0 in gradle.properties.
Also changes the compiled jar name's prefix from pravega to schemaregistry. 
> Issue 134: Change pravega version to 0.8.0

- gradle.properties
Change version to 0.1.1-SNAPSHOT in r0.1
Fixes #137 
in gradle.properties it changes version to 0.1.1-SNAPSHOT in r0.1
All tests should pass.
> Issue 137: Change version to 0.1.1-SNAPSHOT in r0.1

- build.gradle
- contract/src/main/java/io/pravega/schemaregistry/contract/transform/ModelHelper.java
- contract/src/test/java/io/pravega/schemaregistry/contract/transform/ModelHelperTest.java
- server/src/test/java/io/pravega/schemaregistry/server/rest/resources/SchemaRegistryResourceTest.java
Adds a null check to throw appropriate exception when unknown policy is used to create a group.
Fixes #119 
An if statement is added before the switch statement of the overloaded decode method (for Compatibility) in the ModelHelper class. The if statement checks to see if `compatibility.getPolicy()` is null and if so, throws an Illegal Argument exception with the message  `Unknown Compatibility Type`.
Create a group with unknown compatibility policy.
> Issue119: Better Exception Handling for Unknown Policies when Creating a Group.

- build.gradle
Makes pravega client compileonly dependency
Fixes #156 
Updates build.gradle to make pravega client compile only dependency. 
Schema registry serializers depend on pravega Serializer interface which they provide an implementation for. So they take a dependency on pravega client for it.
For `Serializers` we have a "serializers:shared" project which earlier had compile dependency on pravega-client and serializers:avro etc took dependency on serializers:shared.
now we make pravega client dependency `compile only` so we dont bundle pravega client with schema registry serializers.
so this is changed in `serializers:shared` and since pravega client is only …
> Issue 156: Make pravega client compileOnly dependency

- charts/schema-registry/templates/service.yaml
- charts/schema-registry/values.yaml
Being able to pass annotations or labels for the service that schema registry deploys is useful. Easier to manager and track it with other components deployed on a K8s cluster this way (based on putting some annotations on the service).
It is pretty minute code change.
You can test it out with various values files like this:
```
helm install schema charts/schema-registry --debug --dry-run -f values.yaml
```
> Passthrough labels and annotations for the service.

- server/src/main/java/io/pravega/schemaregistry/server/rest/ServiceConfig.java
- server/src/main/java/io/pravega/schemaregistry/server/rest/auth/AuthHandlerManager.java
- server/src/main/java/io/pravega/schemaregistry/service/Config.java
- server/src/test/java/io/pravega/schemaregistry/server/rest/auth/AuthHandlerManagerTest.java
Fixes issue in disable basic auth flag which was not enforced in auth handler manager. 
Fixes #152 
Adds a new config value in ServiceConfig for disabling basic auth. Enforces that policy in AuthHandlerManager while loading auth handlers. 
Unit test added.
> Issue 152: Disable basic auth was not enforced

- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClient.java
- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClientImpl.java
- client/src/test/java/io/pravega/schemaregistry/client/SchemaRegistryClientTest.java
Adds getNamespace api on schemaregistry client. 
Fixes #168 
Adds new api for getting the namespace on schema registry client. 
Unit test added.
> Issue 168: Get namespace api on SchemaRegistryClient

- build.gradle
Makes pravega-common and pravega-shared-auth compile only dependency on client modules.
Fixes #174 
Makes praveg common and pravega shared auth as compile only dependencies on pravega client libraries. 
When schema registry clients are used with pravega applications, the pravega client dependency will bring in the requisite dependencies.
However, if schema registry client is used standalone, then users will need to include additional dependencies for pravega-common. 
> Issue 174: Make pravega-common and pravega-shared-auth compile only dependency

- build.gradle
While including slf4j we should make sure it does not clash with any transitive dependency that we include so we should explicitly exclude it. 
also, add slf4j dependency explicitly. 
Fixes #182 
Adds slf4j dependency explicitly to schema registry server. and exclude slf4j from other dependencies. 
All tests should pass and docker run should show the logs
> Issue 182: Add explicit dependency on slf4j and exlude it from other dependencies

- client/src/main/java/io/pravega/schemaregistry/client/SchemaRegistryClientImpl.java
- client/src/test/java/io/pravega/schemaregistry/client/TestSchemaRegistryClient.java
- server/src/main/java/io/pravega/schemaregistry/storage/client/TableStore.java
- server/src/test/java/io/pravega/schemaregistry/storage/client/TablesStoreTest.java
- server/src/test/java/io/pravega/schemaregistry/storage/client/WireCommandMock.java
Fixes two problems as were found in issue 184:
1. Registry doesnt retry on auth failures but fails the rest call with internal server 500. we should retry on auth failures too. 
2. on registry client in two apis, `latest schema` and `listcodecs` we actually read entity before checking if the entity is indeed present which would be the case when the return code is http.ok.
Fixes #184
Changes retry condition in tablestore to also retry on auth exception.
Fixes the registry client for two apis where we read entity only if the response was success.
Unit tests added
> Issue 184: Retry on auth failures in calls to segment store

- build.gradle
Change json-schema dependency to use maven central
Fixes #180 
Changed to use `group: 'com.github.erosb', name: 'everit-json-schema'` and remove the mulesoft repo
Build and tests pass
> Issue 180: Change json-schema dependency to use maven central

- gradle.properties
Changes to use latest pravega keycloak client version 0.9.0-36.ad03b19-SNAPSHOT
Fixes #179 
uses latest keycloak client version
> Issue 179: Use latest pravega key cloak client library version

- build.gradle
- server/src/main/java/io/pravega/schemaregistry/storage/impl/group/Group.java
- server/src/test/java/io/pravega/schemaregistry/storage/impl/group/GroupPravegaTest.java
- server/src/test/java/io/pravega/schemaregistry/storage/impl/group/GroupTest.java
Use latest version instead of latest Id when computing the previous version for latest schema deletion.
Fixes #187 
The deleteSchema (id,etag) method erroneously uses latest id instead of latest version when computing the previous highest non-deleted schema version for the type. The fix changes the previous version computation to use latest version for the type instead of latest id.
Run the schema delete unit test in GroupTest.java
> Fix bug in schema deletion

- server/src/main/java/io/pravega/schemaregistry/storage/client/TableStore.java
- server/src/test/java/io/pravega/schemaregistry/storage/client/TablesStoreTest.java
Token failure exception for upadteTableEntries should be retried. 
Fixes #189 
Adds a retry logic for updateTableEntries for the token failure exception. 
Unit test added.
> Issue 189: Token failure should be retried for updateTable calls

- build.gradle
- gradle.properties
Changes pravega and keycloak dependency to 0.9.0.
Fixes #192 
Changes pravega and keycloak dependency to 0.9.0.
Also adds dependency on javax.activation as applications otherwise have to take explicit dependency on it. 
All tests should pass.
> Issue 192: Change pravega and keycloak dependencies to 0.9.0

- build.gradle
Signed-off-by: SaiCharan <kotlasaicharan@yahoo.com>
1. `Logback` is added to the compile dependency in `build.gradle.`
2. Any changes in `server/src/conf/logback.xml` are not reflected being of this dependency being missed out.
3. Timestamp is attached to logs. Below are example logs.
```
2021-07-28 03:20:16,344 478  [main] INFO  i.p.schemaregistry.service.Config - java.vm.name = OpenJDK 64-Bit Server VM
2021-07-28 03:20:16,344 478  [main] INFO  i.p.schemaregistry.service.Config - java.vendor.url.bug = https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
2021-07-28 03:20:16,344 478  [main] INFO  i.p.schemaregistry.service.Config - user.dir = /home/saicharan/schema-registry/build/distributions/schema-registry-0.3.0-66.ae51296-SNAPSHOT
2021-07-28 03:20:16,344 …
```
> Issue 205: Enabled Timestamps in Schema Registry logs

- charts/schema-registry/README.md
- charts/schema-registry/templates/deployment.yaml
- charts/schema-registry/values.yaml
Updates the Helm chart to allow custom annotations to be expressed on the final Schema registry PODs
Fixes #208 
Provides a `podAnnotations` value on the Helm chart allowing custom POD annotations to be expressed.  The value of the `podAnnotations` is copied to the final `deployment` template
Using the following values file called "values.txt"
```
podAnnotations:
first: one
second: two
```
`helm install schema-registry charts/schema-registry --values values.txt`
The following shows the final output:
```
spec:
progressDeadlineSeconds: 600
replicas: 2
revisionHistoryLimit: 10
selector:
matchLabels:
app.kubernetes.io/name: schema-registry
strategy:
rollingUpdate:
maxSurge: 25% …
```
> issue-208 Add support for Custom POD Annotations

- .github/workflows/build.yml
This changes the target location where optional snapshot are published.   Git Hub Packages versus Jcenter.
Fixes #214 
Make schema registry snapshots available.
See description.
See tests https://github.com/sarlaccpit/schema-registry/actions/runs/1079214284
> Issue 214:  publish snapshot to Git Hub Packages

- .github/workflows/build.yml
Signed-off-by: Christophe Balczunas <christophe.balczunas@emc.com>
Typo in GH action condition causes snapshots to be skipped even with a push to master branch.
Fixes #217 .  Enables snapshots for master branch.
Fixed the typo.
Unfortunately, there is no easy way to validate it until it gets merged to master.
> Issue 217: fix master branch refs typo in GH action condition

- build.gradle
- gradle.properties
This PR updates the Keycloak client to be in line with the Flink and Spark connectors that use a 0.10.0 snapshot of that library.
(consequently, a switch to use GH packages is also added since snapshots come from there now).
Most importantly, a force override of the netty libraries is added such that the same runtime versions as Pravega client are used.  This allows TLS1.3 connections to be possible
Fixes https://github.com/pravega/schema-registry/issues/209
See description
Tested Schema registry in an environment where Pravega is deployed with TLS1.3 connectivity only.
Tested with a test program that the schema registry client is not affected by this.
> Issue-209: updates netty and Keycloak client libraries

- build.gradle
- gradle.properties
Change various dependencies which were identified as potential vulnerable across the project
Fixes #212 
Change few of the existing library dependencies to a higher version
com.fasterxml.jackson.core_jackson-databind - 2.9.8 -> 2.9.11
org.yaml_snakeyaml - 1.23 -> 1.26
org.apache.commons_commons-compress - 1.18 -> 1.19
All tests and build should go successful, the changed lib versions shouldn't be caught in further scans
> Issue 212: Change dependencies with vulnerability

- server/src/conf/schema-registry.config.properties
There is a typo in the SR config properties for the variable `schemaRegistry.store.pravega.controller.connect.auth.token` which is currently accepting the wrong value `CONTROLLER_AUTH_METHOD` while it should read `CONTROLLER_AUTH_TOKEN` instead.
Fixes #229 
Update the conf property with correct value
> Update SR config properties with correct auth token

- build.gradle
- gradle.properties
Remove forced netty version from build.gradle causing conflicts with Pravega higher versions
fixes #240 
The build should pass and all existing test cases should complete successfully
> Issue 240: Remove Netty dependencies

- gradle.properties
Update the Pravega  and KeyCloak version to 0.11.0. Also, upgraded Zookeeper version due to dependency conflict.
Fixes #244.
Update the Pravega  and KeyCloak version to 0.11.0. Also, upgraded Zookeeper version due to dependency conflict.
Signed-off-by: Raúl Gracia <raul.gracia@emc.com>
> Issue 244: Prepare for 0.4.0 release

- gradle.properties
Set schema registry version to 0.4.0.
Fixes #246.
Set schema registry version to 0.4.0.
Signed-off-by: Raúl Gracia <raul.gracia@emc.com>
> Issue 246: Update branch version to 0.4.0 in r0.4 branch

- gradle.properties
Promote master to 0.5-snapshot as part of 0.4 release.
Fixes #248.
Promote master to 0.5-snapshot as part of 0.4 release.
Signed-off-by: Raúl Gracia <raul.gracia@emc.com>
> Issue 248: Upgrade Schema Registry version to 0.5.0-SNAPSHOT

- charts/schema-registry/values.yaml
Updated the default Controller URI to match the default pravega helm charts since localhost would not be valid given the image used in the k8 helm chart environment.
Fixes #250 
Updates the default controllerUri value in values.yaml file
Follow the [Pravega Kubernetes 101 Guide](https://cncf.pravega.io/docs/nightly/getting-started/pravega-on-kubernetes-101/) and then install the schema registry charts with default values.
> Issue-250 Default Helm Chart value for controllerUri

- build.gradle
Produce compressed .tgz release assets instead of uncompressed .tar assets.
Fixes #261
Sets gzip as the compression for Tar tasks in the gradle build.
`./gradlew clean distribution` and note *.tgz files in `build/distribution`.
> Issue 261: Compress distribution tar files using gzip

- charts/schema-registry/Chart.yaml
- charts/schema-registry/values.yaml
- documentation/src/docs/pravega-applications.md
Current version of charts and values.yaml uses the older release of Schema Registry. This needs to be updated to current version.
Fixes #263 
Update the version of current Schema Registry in charts and values.yaml
Current version(0.5.0) should be reflected in the charts and values.yaml with updated version ref in Pravega-Applications.md
> Issue-263 Update Schema Registry Release Version in charts

- gradle.properties
Change log description
Promote master to 0.6-snapshot as 0.5 is released.
Purpose of the change
Fixes #267 .
What the code does
Promote master to 0.6-snapshot.
How to verify it
> Issue 267: Promote master to 0.6.0-Snapshot

- gradle.properties
Set Schema Registry version to 0.5.1-SNAPSHOT.
Fixes #271.
Set Schema Registry version to 0.5.1-SNAPSHOT.
Build should pass.
> Issue 271: Bump r0.5 to 0.5.1-SNAPSHOT

- gradle.properties
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Upgrade dependencies in …
> Issue 279: change snakeyaml version

- gradle.properties
Update the Pravega and KeyCloak version to 0.13.0 and SR version to 0.6.0
Fixes #285 
Update the Pravega, KeyCloak and SR version
The build must pass
> Issue 285: Prepare Schema Registry for 0.6 release

- gradle.properties
**Change log description**
Promote master to 0.7-snapshot as part of 0.6 release.
**Purpose of the change**
Fixes #283 .
**What the code does**
Promote master to 0.7-snapshot as part of 0.6 release.
**How to verify it**
> Issue 283: Upgrade Schema Registry version to 0.7.0-SNAPSHOT
